"""
agent.py  —  SmartAgentDecisionLayer
======================================
Design contract:
  • LLM owns ALL reasoning: intent inference, slot extraction, state tracking,
    and response generation.
  • Python code manages ONLY: session persistence, LLM call infrastructure,
    and retry/fallback (which itself calls LLM, not a template string).
  • Zero hardcoded Hinglish strings in Python. Every word the user hears
    is generated by the LLM.
  • Conversation history is a proper dialogue (User / Agent turns), not a
    debug verbatim log string — makes LLM reasoning dramatically better.
  • Agent remembers what it last asked, does not repeat itself.
  • Intent can be updated mid-conversation if user's purpose changes.
  • User can say "cancel / band karo / naya shuru" to reset the session.
"""

import json
import re
import time
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# ── Session store (Redis with in-memory fallback) ─────────────────────────────
try:
    import redis
    _redis = redis.Redis(host="localhost", port=6379, db=0, decode_responses=True)
    _redis.ping()
    REDIS_AVAILABLE = True
    print("  [SESSION] Redis connected.")
except Exception:
    REDIS_AVAILABLE = False
    print("  [SESSION] Redis unavailable — using in-memory fallback.")

SESSION_TTL = 60 * 60 * 4   # 4 hours


class SessionStore:
    def __init__(self):
        self._mem: dict = {}

    def _key(self, sid: str) -> str:
        return f"entropic:session:{sid}"

    def get(self, sid: str) -> dict | None:
        if REDIS_AVAILABLE:
            raw = _redis.get(self._key(sid))
            return json.loads(raw) if raw else None
        return self._mem.get(sid)

    def set(self, sid: str, data: dict):
        if REDIS_AVAILABLE:
            _redis.setex(self._key(sid), SESSION_TTL, json.dumps(data, ensure_ascii=False))
        else:
            self._mem[sid] = data

    def delete(self, sid: str):
        if REDIS_AVAILABLE:
            _redis.delete(self._key(sid))
        else:
            self._mem.pop(sid, None)


# ── System prompt ─────────────────────────────────────────────────────────────
# Engineering notes for this prompt:
#  1. Compact schema (one line per intent) minimises context for 0.5B model.
#  2. JSON schema on ONE line — model copies the shape, not the formatting.
#  3. Three tight EXAMPLES show the exact Hinglish style required.
#  4. "intent" field in output lets the LLM correct a wrong pipeline label.
SYSTEM_PROMPT = """\
You are Entropic, an intelligent Hinglish voice assistant for India.
You collect structured information through natural conversation in Hinglish (Hindi + English mix).

INTENTS AND REQUIRED FIELDS:
SEND_MONEY→amount,recipient | CHECK_BALANCE→account_type | BILL_PAYMENT→bill_type,amount,biller_name
RECEIVE_MONEY→amount,sender | EXPENSE_LOG→amount,category | FIR_THEFT→incident,amount_stolen,num_perpetrators,time,location,victim_name
FIR_ASSAULT→incident,time,location,victim_name,accused_description | ASSET_DECLARATION→asset_type,size_or_value,location,beneficiary,declarant_name
HEALTH_RECORD→child_age,weight,symptom,household_id | UNKNOWN→clarify intent first

OUTPUT — one line of valid JSON, nothing else:
{"intent":"...","extracted":{"f":"v"},"all_collected":{"f":"v"},"still_needed":["f1"],"status":"incomplete","response":"hinglish message"}

RULES:
1. response must be Hinglish (Hindi+English mix). NEVER pure English.
2. Extract ONLY what user explicitly said. Never invent values.
3. Ask ONE question per turn for the single most important missing field.
4. Set status="complete" when all required fields are filled.
5. If intent=UNKNOWN, ask what user wants in Hinglish.
6. If audio_tier=HARD_REPROMPT, ask user to speak clearly in Hinglish.
7. Use "intent" field to correct a wrong pipeline label when you are certain.

EXAMPLES (copy exact style):
{"intent":"SEND_MONEY","extracted":{"amount":"1000","recipient":"Rahul"},"all_collected":{"amount":"1000","recipient":"Rahul"},"still_needed":[],"status":"complete","response":"Bilkul! 1000 rupay Rahul ko abhi transfer karte hain."}
{"intent":"UNKNOWN","extracted":{},"all_collected":{},"still_needed":[],"status":"incomplete","response":"Namaste! Aap kya karna chahte hain — paisa bhejna, balance check, ya kuch aur?"}
{"intent":"FIR_THEFT","extracted":{"incident":"chori","amount_stolen":"5000","num_perpetrators":"3"},"all_collected":{"incident":"chori","amount_stolen":"5000","num_perpetrators":"3"},"still_needed":["time","location","victim_name"],"status":"incomplete","response":"Samajh gaya. Yeh chori kab aur kahan hui thi?"}
{"intent":"SEND_MONEY","extracted":{},"all_collected":{"amount":"500"},"still_needed":["recipient"],"status":"incomplete","response":"500 rupay — theek hai. Yeh kisko bhejna hai?"}
"""

# ── Constants ─────────────────────────────────────────────────────────────────
# Words that signal user wants to cancel / restart
RESET_TRIGGERS = {
    "cancel", "band karo", "bandh karo", "naya shuru", "start over",
    "chodo", "chod do", "rukk jao", "stop", "wapas jao", "reset",
    "nahin", "nahi karna", "rehne do",
}

# Valid intent labels (used to validate LLM output)
VALID_INTENTS = {
    "SEND_MONEY", "CHECK_BALANCE", "BILL_PAYMENT", "RECEIVE_MONEY",
    "EXPENSE_LOG", "FIR_THEFT", "FIR_ASSAULT", "ASSET_DECLARATION",
    "HEALTH_RECORD", "UNKNOWN",
}


def new_session() -> dict:
    return {
        "intent":          None,
        "collected_slots": {},
        "dialogue":        [],   # list of {"role": "user"|"agent", "text": "...", "meta": {}}
        "turns":           0,
        "last_agent_msg":  "",   # what agent asked last, to avoid repetition
        "eval": {
            "total_turns":    0,
            "hard_reprompts": 0,
            "soft_reprompts": 0,
            "accepts":        0,
            "avg_confidence": 0.0,
            "conf_samples":   [],
        }
    }


class SmartAgentDecisionLayer:
    def __init__(self, model_id: str = "Qwen/Qwen2.5-0.5B-Instruct"):
        self.store = SessionStore()
        print(f"Loading Smart Agent LLM ({model_id})...")
        self.tokenizer = AutoTokenizer.from_pretrained(model_id)

        try:
            torch.cuda.empty_cache()
            self.llm = AutoModelForCausalLM.from_pretrained(
                model_id, torch_dtype=torch.float16
            ).to(DEVICE)
        except Exception as e:
            print(f"  [WARN] LLM GPU load failed ({e}). Falling back to CPU float32.")
            self.llm = AutoModelForCausalLM.from_pretrained(
                model_id, torch_dtype=torch.float32
            ).to("cpu")

        self.llm_device = self.llm.device
        print(f"  [✓] LLM loaded on {self.llm_device}.")

    # ── Low-level generation ──────────────────────────────────────────────────
    def _generate(self, messages: list[dict], max_new_tokens: int = 200,
                  greedy: bool = False) -> str:
        text   = self.tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )
        inputs = self.tokenizer([text], return_tensors="pt").to(self.llm_device)
        with torch.no_grad():
            out = self.llm.generate(
                **inputs,
                max_new_tokens=max_new_tokens,
                do_sample=not greedy,
                temperature=0.25 if not greedy else 1.0,
                top_p=0.9,
                pad_token_id=self.tokenizer.eos_token_id,
            )
        return self.tokenizer.decode(
            out[0][inputs.input_ids.shape[1]:], skip_special_tokens=True
        ).strip()

    # ── Dialogue history formatter ────────────────────────────────────────────
    def _format_dialogue(self, session: dict) -> str:
        """
        Formats session dialogue as a readable conversation for the LLM.
        Far better than a debug verbatim log — the LLM can reason over
        a natural-looking conversation instead of parsing metadata strings.
        """
        lines = []
        for entry in session["dialogue"][-8:]:   # last 8 turns (4 exchanges)
            role   = "User" if entry["role"] == "user" else "Agent (you)"
            meta   = entry.get("meta", {})
            suffix = ""
            if entry["role"] == "user" and meta:
                suffix = f" [tier={meta.get('tier','?')}, conf={meta.get('conf',0):.2f}, pipeline_intent={meta.get('intent','?')}]"
            lines.append(f"  {role}: \"{entry['text']}\"{suffix}")
        return "\n".join(lines) if lines else "  (no history — this is the first turn)"

    # ── Intent inference for UNKNOWN cases ───────────────────────────────────
    def _llm_infer_intent(self, transcript: str) -> str:
        """
        Greedy 8-token call: asks LLM to classify intent when DistilBERT
        returned UNKNOWN. Handles English, mixed, and ambiguous utterances.
        """
        user_msg = (
            f'What financial/civic intent does this user utterance express?\n'
            f'User said: "{transcript}"\n\n'
            f'Pick EXACTLY ONE label:\n'
            f'SEND_MONEY | CHECK_BALANCE | BILL_PAYMENT | RECEIVE_MONEY | '
            f'EXPENSE_LOG | FIR_THEFT | FIR_ASSAULT | ASSET_DECLARATION | '
            f'HEALTH_RECORD | UNKNOWN\n\n'
            f'Output ONLY the label.'
        )
        raw = self._generate(
            [
                {"role": "system", "content": "You are an intent classifier. Output ONLY the intent label."},
                {"role": "user",   "content": user_msg},
            ],
            max_new_tokens=8,
            greedy=True,
        )
        label = raw.split()[0].upper() if raw.split() else "UNKNOWN"
        return label if label in VALID_INTENTS else "UNKNOWN"

    # ── Main LLM reasoning call ───────────────────────────────────────────────
    def _llm_reason(self, session: dict, transcript: str,
                    intent: str, conf: float, tier: str) -> dict:
        """
        Core LLM call — the LLM sees the full conversation dialogue,
        the current turn's pipeline metadata, and all previously collected info.
        It decides: what to extract, what's missing, what to say next.
        """
        dialogue_str = self._format_dialogue(session)
        collected    = session.get("collected_slots", {})
        last_asked   = session.get("last_agent_msg", "")

        user_msg = (
            f"CONVERSATION SO FAR:\n{dialogue_str}\n\n"
            f"NEW USER TURN:\n"
            f"  said       : \"{transcript}\"\n"
            f"  intent     : {intent}\n"
            f"  confidence : {conf:.2f}\n"
            f"  audio_tier : {tier}\n\n"
            f"ALREADY COLLECTED:\n"
            f"  {json.dumps(collected, ensure_ascii=False) if collected else '(nothing yet)'}\n\n"
            f"YOUR LAST MESSAGE WAS: \"{last_asked}\"\n"
            f"Do not repeat the same question. "
            f"Extract new info, update collected fields, respond in Hinglish. Return JSON only."
        )

        raw = self._generate(
            [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user",   "content": user_msg},
            ],
            max_new_tokens=230,
        )

        # Try to parse JSON — be generous (find first complete {...} block)
        try:
            match = re.search(r'\{.*\}', raw, re.DOTALL)
            if match:
                data = json.loads(match.group(0))
                # Normalise key names (sometimes LLM uses "hinglish_response")
                if "hinglish_response" in data and "response" not in data:
                    data["response"] = data.pop("hinglish_response")
                data.setdefault("intent",        intent)
                data.setdefault("extracted",     {})
                data.setdefault("all_collected", collected)
                data.setdefault("still_needed",  [])
                data.setdefault("status",        "incomplete")
                data.setdefault("response",      "")
                return data
        except Exception:
            pass

        # JSON parse failed → fallback: ask LLM just for a Hinglish sentence
        return self._llm_fallback_response(intent, tier, collected, last_asked)

    # ── Retry fallback (NOT a template — still uses the LLM) ─────────────────
    def _llm_fallback_response(self, intent: str, tier: str,
                                collected: dict, last_asked: str) -> dict:
        """
        When the main LLM call fails to produce valid JSON, make a simpler
        call asking ONLY for a Hinglish sentence. Still LLM-generated.
        No hardcoded strings.
        """
        tier_instructions = {
            "HARD_REPROMPT": "Audio was unclear. Tell user to speak more clearly and repeat.",
            "SOFT_REPROMPT": "You were not sure what user said. Ask for gentle clarification.",
            "ACCEPT":        "Ask for the next most important missing piece of information.",
        }
        instruction = tier_instructions.get(tier, "Ask user what they need.")

        user_msg = (
            f"You are a Hinglish voice assistant.\n"
            f"Intent being handled: {intent if intent != 'UNKNOWN' else 'unknown — ask what user wants'}\n"
            f"Already collected: {json.dumps(collected, ensure_ascii=False) if collected else 'nothing'}\n"
            f"Your last message was: \"{last_asked}\"\n"
            f"Instruction: {instruction}\n\n"
            f"Write ONE short Hinglish response (2-3 sentences, mix Hindi+English). "
            f"Do not repeat the last question. Output ONLY the response text."
        )
        response_text = self._generate(
            [
                {"role": "system", "content": "You write short Hinglish voice responses."},
                {"role": "user",   "content": user_msg},
            ],
            max_new_tokens=80,
        )
        # Sanitise — take first two sentences if LLM rambles
        sentences = re.split(r'(?<=[.!?])\s+', response_text.strip())
        response_text = " ".join(sentences[:2])

        return {
            "intent":        intent,
            "extracted":     {},
            "all_collected": collected,
            "still_needed":  [],
            "status":        "incomplete",
            "response":      response_text,
        }

    # ── Eval tracking ─────────────────────────────────────────────────────────
    def _update_eval(self, session: dict, tier: str, conf: float):
        e = session["eval"]
        e["total_turns"] += 1
        if   tier == "ACCEPT":        e["accepts"]        += 1
        elif tier == "SOFT_REPROMPT": e["soft_reprompts"] += 1
        else:                         e["hard_reprompts"] += 1
        e["conf_samples"].append(conf)
        e["avg_confidence"] = round(sum(e["conf_samples"]) / len(e["conf_samples"]), 4)

    # ── Session reset check ───────────────────────────────────────────────────
    def _is_reset_command(self, transcript: str) -> bool:
        t = transcript.lower()
        return any(w in t for w in RESET_TRIGGERS)

    # ── Main entry point ──────────────────────────────────────────────────────
    def process_turn(self, session_id: str, pipeline_output: dict) -> dict:
        session  = self.store.get(session_id) or new_session()
        session["turns"] += 1

        transcript = pipeline_output.get("transcript", "")
        tier       = pipeline_output.get("status", "ACCEPT")
        intent     = (
            pipeline_output.get("intent_raw")
            or pipeline_output.get("intent", "UNKNOWN").split(" ")[0]
        )
        conf    = pipeline_output.get("confidence", 0.0)
        amount  = pipeline_output.get("amount", "UNKNOWN")
        latency = pipeline_output.get("latency", {})

        # ── Session reset ─────────────────────────────────────────────────────
        if self._is_reset_command(transcript):
            self.store.delete(session_id)
            reset_reply = self._generate(
                [
                    {"role": "system", "content": "You are a Hinglish voice assistant."},
                    {"role": "user",   "content":
                     "User wants to start over or cancel. Write a short Hinglish acknowledgement "
                     "(one sentence, mix Hindi+English). ONLY the response text."},
                ],
                max_new_tokens=40,
            ).strip()
            return {
                "status":      "reset",
                "agent_prompt": reset_reply,
                "latency":     latency,
            }

        # ── Update eval stats ─────────────────────────────────────────────────
        self._update_eval(session, tier, conf)

        # ── Add user turn to dialogue ─────────────────────────────────────────
        session["dialogue"].append({
            "role": "user",
            "text": transcript,
            "meta": {"tier": tier, "conf": conf, "intent": intent},
        })

        # ── Resolve active intent ─────────────────────────────────────────────
        # (1) Pipeline gave a known intent → use it
        if intent not in ("UNKNOWN", "", None) and not session["intent"]:
            session["intent"] = intent

        # (2) Pipeline gave UNKNOWN → try LLM to infer
        if not session["intent"] and intent == "UNKNOWN":
            try:
                inferred = self._llm_infer_intent(transcript)
                if inferred != "UNKNOWN":
                    session["intent"] = inferred
                    session["dialogue"][-1]["meta"]["llm_intent"] = inferred
            except Exception as e:
                print(f"  [WARN] LLM intent inference failed: {e}")

        # (3) Pre-populate amount field from pipeline NER if pipeline found one
        #     Only if we already know the intent to avoid polluting FIR sessions
        if amount not in ("UNKNOWN", "", None) and session["intent"]:
            session["collected_slots"].setdefault("amount", amount)

        # ── Core LLM reasoning ────────────────────────────────────────────────
        llm_out = self._llm_reason(
            session,
            transcript,
            session["intent"] or intent,
            conf,
            tier,
        )

        # ── Let LLM update intent if it is confident ──────────────────────────
        llm_intent = str(llm_out.get("intent", "")).strip().upper()
        if llm_intent in VALID_INTENTS and llm_intent != "UNKNOWN":
            session["intent"] = llm_intent   # LLM can correct wrong pipeline label

        # ── Merge slot extractions — LLM is the authority ─────────────────────
        # Code only skips obvious null-like values
        _skip = {"unknown", "none", "null", "", "n/a", "not provided"}
        for src in (llm_out.get("extracted", {}), llm_out.get("all_collected", {})):
            for k, v in src.items():
                v_str = str(v).strip()
                if v_str.lower() not in _skip:
                    session["collected_slots"].setdefault(k, v_str)

        still_needed  = llm_out.get("still_needed", [])
        status        = llm_out.get("status", "incomplete")
        agent_reply   = llm_out.get("response", "")

        # ── Store agent response in dialogue ──────────────────────────────────
        session["dialogue"].append({
            "role": "agent",
            "text": agent_reply,
        })
        session["last_agent_msg"] = agent_reply

        # ── Completion ────────────────────────────────────────────────────────
        if status == "complete":
            final_record = {
                "intent":      session["intent"],
                "total_turns": session["turns"],
            }
            final_record.update(session["collected_slots"])
            final_record["dialogue"] = [
                {"role": e["role"], "text": e["text"]}
                for e in session["dialogue"]
            ]
            eval_summary = session["eval"]
            self.store.delete(session_id)

            return {
                "status":        "complete",
                "message":       "All information collected. Structured record ready.",
                "final_record":  final_record,
                "eval_summary":  eval_summary,
                "agent_prompt":  agent_reply or "Shukriya! Record save ho gayi.",
                "latency":       latency,
            }

        # ── Incomplete — continue conversation ────────────────────────────────
        self.store.set(session_id, session)
        return {
            "status":          "incomplete",
            "intent":          session["intent"],
            "missing_slots":   still_needed,
            "collected_slots": session["collected_slots"],
            "agent_prompt":    agent_reply,
            "turn":            session["turns"],
            "latency":         latency,
            "eval":            session["eval"],
        }


# ── Smoke test ────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    agent = SmartAgentDecisionLayer()

    def run(label: str, turns: list[dict]):
        print(f"\n{'='*60}\n  {label}\n{'='*60}")
        sid = f"smoke_{int(time.time())}_{label[:10].replace(' ','_')}"
        for i, t in enumerate(turns, 1):
            print(f"\n[Turn {i}] '{t['transcript']}'  conf={t['confidence']}  tier={t['status']}")
            r = agent.process_turn(sid, t)
            if r["status"] == "complete":
                print("✅ COMPLETE")
                print(json.dumps(r["final_record"], indent=2, ensure_ascii=False))
            elif r["status"] == "reset":
                print(f"🔄 RESET: {r['agent_prompt']}")
            else:
                print(f"🎙️  {r.get('agent_prompt', '[no response]')}")
                print(f"    intent={r.get('intent')}  "
                      f"collected={r.get('collected_slots', {})}  "
                      f"missing={r.get('missing_slots', [])}")

    run("1. Send Money — clear utterance", [
        {"status": "ACCEPT",       "transcript": "1000 rupay Rahul ko bhej do",
         "intent_raw": "SEND_MONEY", "amount": "1000", "confidence": 0.91, "latency": {}},
    ])

    run("2. FIR Theft — multi-turn", [
        {"status": "ACCEPT",       "transcript": "kal raat dukaan mein ghuse teen log paanch hazaar le gaye",
         "intent_raw": "UNKNOWN",   "amount": "5000", "confidence": 0.55, "latency": {}},
        {"status": "ACCEPT",       "transcript": "model town amritsar, raat das baje tha",
         "intent_raw": "UNKNOWN",   "amount": "UNKNOWN", "confidence": 0.72, "latency": {}},
        {"status": "ACCEPT",       "transcript": "mera naam ramesh sharma hai",
         "intent_raw": "UNKNOWN",   "amount": "UNKNOWN", "confidence": 0.79, "latency": {}},
    ])

    run("3. Session reset mid-conversation", [
        {"status": "ACCEPT",       "transcript": "500 rupay bhej do priya ko",
         "intent_raw": "SEND_MONEY","amount": "500", "confidence": 0.88, "latency": {}},
        {"status": "ACCEPT",       "transcript": "cancel karo yaar, rehne do",
         "intent_raw": "UNKNOWN",   "amount": "UNKNOWN", "confidence": 0.40, "latency": {}},
    ])

    run("4. English OOD — LLM intent fallback", [
        {"status": "HARD_REPROMPT","transcript": "Hello my name is Krishpunjh I work here",
         "intent_raw": "UNKNOWN",   "amount": "UNKNOWN", "confidence": 0.28, "latency": {}},
        {"status": "ACCEPT",       "transcript": "mujhe apna balance check karna hai",
         "intent_raw": "CHECK_BALANCE","amount": "UNKNOWN", "confidence": 0.81, "latency": {}},
    ])